### PR TITLE
NHEK

### PR DESCRIPTION
**Pull request by addruart**
This is the addition to the code of the near-horizon geodesics. I have added a tutorial notebook in the documentation to explain how the new functions added work.

### CODE REVIEW

**Comment by nielsw2** [comment]
Hi Adrien, thanks for new NHEK code. The changes shouldn't have been merged into master though as we need to review them first. I will revert the merge now and will look over the additions in the coming week or two. I'm sure the code is working fine but we need to think carefully about the API (which may be fine but needs to be reviewed first).

**Comment by nielsw2** [comment]
@addruart I've revert the changes to master. Could you create the pull request again?

**Comment by addruart** [comment]
Ah ok, @nielsw2 ! I am not fully used to github now, so I wasn't sure what was the exact procedure to follow... I create the pull request again !

**Comment by addruart** [comment]
I cannot create the pull request, because "master is up to date with all commits from NHEK"... hope I haven't broken everything...

**Comment by duetosymmetry** [comment]
@addruart , the current master is now ahead of your tree, because @nielsw2 added the revert commits onto the end. @nielsw2 this is a rare occasion when I would actually suggest doing a force-push to rewind master... as long as nobody has cloned in the past 3 hours

**Comment by addruart** [comment]
@duetosymmetry, have I to do something from my account ? Or let you handle the situation until further notice ?

**Comment by nielsw2** [comment]
@duetosymmetry thanks for the tip. I guess I could also merge master into the NHEK branch and then we can create the pull request?

@addruart the great thing about git is the version history so nothing can really get broken. We can sort this out and then you can create a new pull request.

I think we can set up controls so that only certain people can merge into master. I'll take a look at that as it would stop this situation from happening.

**Comment by addruart** [comment]
Ok, @nielsw2 ! Let me know when I can create the pull request again. Sorry for the mistake...

**Comment by nielsw2** [comment]
Looks like merging master into NHEK wont work as I already merged the revert commits which then try to delete things from the NHEK branch. I'll try to rewind master as @duetosymmetry suggested.

**Pull request merged**
