### PR TITLE
(Partially) fix Constants of Motion and Frequencies for e=1 orbits

### PR DESCRIPTION
**Pull request by MvdMeent**
This contains some old fixes to the KerrGeodesics package, which need to be reviewed and merged into the main branch.

### CODE REVIEW

**Comment by nielsw2** [comment]
@ofl23 Do you have code to check the e=1 AngularMomentum, RadalRoots, and Frequencies code that Maarten has added?

**Comment by ofl23** [comment]
@nielsw2 I have codes that can calculate AngularMomentum and RadialRoots for e>1. I will check if they are also valid for the  boundary case.

**Comment by ofl23** [comment]
I have checked AngularMomentum for e=1 for Schwarzschild and I agree. I don't have valid formulae for the RadialRoots or Frequencies so I haven't been able to check those.

**Review by nielsw2 — APPROVED** [review]
I checked all the remaining e=1 functions where the numerical limit of the general functions.

**Pull request merged**
