### PR TITLE
Four velocity

### PR DESCRIPTION
**Pull request by Philip-Lynch**
Added a new subpackage and documentation for KerrGeoVelocity. 
Made it so that KerrGeoOrbit calls KerrGeoVelocity and adds the velocity components to the outputted association.
Made some changes to KerrGeoOrbitEquatorialDarwin so that it would pass some unit tests, but feel free to overwrite them if they conflict with Maarten's changes.

### CODE REVIEW

**Comment by nielsw2** [comment]
This is looking very nice. I changed the output to be either "u^t" or "u_t", etc, depending on whether we're coming the contra- or co-variant four-velocity.

A few other thoughts:

- we should be clear in the documentation what our normalization is, i.e., u^a u_a  = -1.
- I think we should call the function KerrGeoFourVelocity[..] as it is not clear if `Velocity` is the four- or three-velocity.
- I noticed when I set e=0 there is a 1/0 error warning but it looked like the results come out ok. It probably makes sense to use simpler formula in these special cases which will fix this.
- @MvdMeent recently changed the master branch to return pure functions. We should probably do the same for the KerrGeoFourVelocity function
- We should probably have a numerical calculation as well as the analytic results. @znasipak, you have something like that, or should we use a hybrid approach (which I think both @MvdMeent and @znasipak have developed).

**Comment by Philip-Lynch** [comment]
Hi Niels. Thanks for those additions. 

- I'd be happy to include a note on the normalization and rename the function to FourVelocity as it is less ambiguous. I'll also look into using pure functions. 

- I have only gotten that error for polar orbits (x = 0) where KerrGeoOrbit breaks down anyway. I can't seem to replicate that for e=0. Which parameters were you using?

**Comment by nielsw2** [comment]
@Philip-Lynch It looks like I only see the `1/0` issue for the Darwin parameterization, e.g.,

`KerrGeoVelocity[0.9, 10, 0, 1, "Index" -> "Contravariant", "Parametrization" -> "Darwin"]`

**Comment by Philip-Lynch** [comment]
- I made the changes you asked and fixed the 1/0 error. 

- I noticed an edge case where the velocity doesn't normalize to -1 for equatorial circular retrograde orbits. I can't seem to find what the error.

- All other cases seem to work just fine.

**Comment by nielsw2** [comment]
I checked out the changes (though not yet against an independent calculation yet). I changed the association key to "FourVelocity".

When I try the Darwin case I find an error is given for:

`KerrGeoOrbit[0.9, 10, 0, 1, "Parametrization" -> "Darwin", Method -> "Analytic"]`

and no FourVelocity is computed.

For `KerrGeoOrbit[0.9, 10, 0.5, 1, "Parametrization" -> "Darwin"]` there is no error but also no FourVelocity is computed it seems. I can try to dig into this tomorrow.

**Comment by Philip-Lynch** [comment]
Before, I had decided not to add the FourVelocity calculation to the FastSpec functions because I thought it might slow them down too much. But it turns out it barely adds any time at all. 

 I also addressed those two bugs:

`KerrGeoOrbit[0.9, 10, 0, 1, "Parametrization" -> "Darwin", Method -> "Analytic"]`

- Will now give a 1/0 error, but that's due to the nature of the trajectory calculation (Darwin parameter is ill defined for circular orbits), but the velocities are still calculated correctly. 

`KerrGeoOrbit[0.9, 10, 0.5, 1, "Parametrization" -> "Darwin"]`

- Now works correctly

**Pull request merged**
