### PR TITLE
Implement negative a support for constants of motion and frequencies.

### PR DESCRIPTION
**Pull request by MvdMeent**
This contains a number of fixes to the behaviour of the constants of motion and frequencies for retrograde and negative spin orbits. All behaviour should now be conistent, including most (all?) edge cases.

### CODE REVIEW

**Comment by MvdMeent** [comment]
Frequencies for polar orbits should now also work.

**Comment by nielsw2** [comment]
This seems to fix all the negative a issues I can think of to test. It also fixes all the explicit examples raised in issue #22.

@MvdMeent There we some conflicts when I merged the master branch into the MvdM_dev branch. I think I resolved them just fine but maybe take a quick check before we merge this pull request.

If anyone else (@znasipak?) has time to run a few checks that would be great. I plan to merge this pull request tomorrow morning if I don't hear any objections.

**Comment by MvdMeent** [comment]
@nielsw2 There were some minor breaks due to the merge, they are all fixed now.

I have not looked at the behaviour of KerrGeoOrbit and KerrGeoSeparatrix. I can have a brief look at the latter.

**Comment by nielsw2** [comment]
Shouldn't the following give the same result:

```mathematica
KerrGeoSeparatrix[-0.5, 0.5, 1]
KerrGeoSeparatrix[0.5, 0.5, -1]
```

At the moment they don't.

**Comment by nielsw2** [comment]
I've checked and the ISCO, ISSO, IBSO, Separatrix and PhotonSphereRadius all seem to be behaving now.

**Review by nielsw2 — APPROVED** [review]
All the checks I can think of are now passing including for the four-velocity and orbit functions

**Pull request merged**
